### ISSUE TITLE
新增国际国内机型字段

### ISSUE THREAD

**Issue by jebouruama** [jantacy/mobilemodels#1]
感谢提供的工具，但是我发现转换后的csv文件存在很多一个model对应有两条记录的现象（有900多条），这是由于原MD文件分为国内机型和国际机型两种文件，若能增加一个字段，判断文件后缀为en的填入en，否则为cn，这样就能确保导出结果在数据库中应用的唯一性。

**Comment by jantacy** [comment]
改好了。

**Comment by jebouruama** [comment]
神速！非常感谢。
