### ISSUE TITLE
Oneplus解析出现错误型号ONE

### ISSUE THREAD

**Issue by i2end** [jantacy/mobilemodels#3]
解析Oneplus的型号时，诸如ONE A001的型号会被解析成两条，空格切分后的ONE也会被当作型号。同样的还有xiaomi的SHARK前缀系列，honor的HUAWEI前缀系列，letv的Le前缀系列。

**Comment by jantacy** [comment]
> 解析Oneplus的型号时，诸如ONE A001的型号会被解析成两条，空格切分后的ONE也会被当作型号。同样的还有xiaomi的SHARK前缀系列，honor的HUAWEI前缀系列，letv的Le前缀系列。

解决了，但建议找原项目作者提issue，解决一行有多个model的问题，这个规则不太好处理，多看几个品牌就发现规则不太一样。
